[project]
name = "moodle-quiz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypercorn>=0.17.3",
    "kivy>=2.3.0",
    "quart>=0.19.6",
]
